version: "3.7"
services:

  oracle-database:
    image: jplarochedocker/custom-oracle:latest
    ports:
      - target: 1521
        published: 1521
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1073741824 # this means 1GB
    networks:
      - striim_oracle_net
    environment:
      ORACLE_PWD: "tiger"

  striim:
    image: jplarochedocker/custom-striim:latest
    ports:
      - target: 9080
        published: 80
        protocol: tcp
        mode: host
    networks:
      - striim_oracle_net
    environment:
      STRIIM_ACCEPT_EULA: "Y"
    extra_hosts:
    - "zoo1:34.95.11.111"

  java-kstream:
    image: jplarochedocker/custom-kstream:latest
    networks:
      - striim_oracle_net
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/u01/oracle/telus-project-001-7a785be0cc40.json"
    extra_hosts:
    - "zoo1:34.95.11.111"


networks:
  striim_oracle_net:
    driver: overlay

