FROM striim/evalversion

USER root

# docker run --name oracle-database-11.2.0.2-xe --shm-size=1g -p 1521:1521 -p 8080:8080 -e ORACLE_PWD=tiger -v /home/oracle/scripts/setup:/u01/app/oracle/scripts/setup -v /home/oracle/scripts/startup:/u01/app/oracle/scripts/startup -v /home/oracle/oradata:/u01/app/oracle/oradata -d oracle/database:11.2.0.2-xe

COPY striim/ojdbc7-12.1.0.2.jar /opt/striim/lib/ojdbc7-12.1.0.2.jar

RUN  chown -R striim:striim /opt/striim/lib/ojdbc7-12.1.0.2.jar && chmod ug+rwx /opt/striim/lib/ojdbc7-12.1.0.2.jar

RUN  echo "34.95.11.111    kafka_1\n" >> /etc/hosts; echo "35.225.220.10   zoo1\n" >> /etc/hosts; echo "34.66.94.46     zoo2\n" >> /etc/hosts


